<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('logbook_pk_ugd', function (Blueprint $table) {
            $table->id();
            $table->string('no_rm', 6);
            $table->foreign('no_rm')->references('no_rm')->on('pasien');
            $table->enum('serah_terima_dan_mengerjakan_dok_pasien_baru_dewasa_dan_anak', ['sesuai', 'tidak sesuai']);
            $table->enum('memasang_gelang_identitas_pasien_sesuai_prosedur', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_pendokumentasian_assesment_pasien_awal_masuk', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_sbar_dan_tbak', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_pernafasan', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_tekanan_nadi', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_tekanan_darah', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_suhu_tubuh', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_saturasi_oksigen', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_oksigen_inhalasi_o2', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_rjp', ['sesuai', 'tidak sesuai']);
            $table->enum('memasang_catheter', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_heacting', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_dan_mendokumentasikan_7_benar_obat', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_per_oral_po', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_venous_iv', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_muskular_im', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_cutan_ic', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_sub_cutan_sc', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_supositori', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_vaginal', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_mata', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_sublingual', ['sesuai', 'tidak sesuai']);
            $table->enum('menyiapkan_dan_memasang_infus_anak', ['sesuai', 'tidak sesuai']);
            $table->enum('menyiapkan_dan_memasang_infus_dewasa', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_balance_cairan', ['sesuai', 'tidak sesuai']);
            $table->enum('mengoperasionalkan_ctg', ['sesuai', 'tidak sesuai']);
            $table->enum('mengoprasionalkan_ekg', ['sesuai', 'tidak sesuai']);
            $table->enum('memasang_ngt', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_kompres_hangat', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_perawatan_pada_pasien_yang_akan_meninggal', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_perawatan_pada_pasien_baru_meninggal', ['sesuai', 'tidak sesuai']);
            $table->string('catatan')->nullable();
            $table->string('nip', 12);
            $table->foreign('nip')->references('nip')->on('users');
            $table->enum('status_validasi', ['tervalidasi', 'belum tervalidasi'])->default('belum tervalidasi');
            $table->string('validator', 12)->nullable();
            $table->foreign('validator')->references('nip')->on('users');
            $table->timestamp('waktu_validasi')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
        });

        Schema::create('logbook_pk_rawatinap', function (Blueprint $table) {
            $table->id()->primary();
            $table->string('no_rm', 6);
            $table->foreign('no_rm')->references('no_rm')->on('pasien');
            $table->enum('menerima_dan_mengerjakan_dokumentasi_pasien_baru_dewasa_dan_anak', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_sbar_dan_tbak', ['sesuai', 'tidak sesuai']);
            $table->enum('assesment_resiko_jatuh', ['sesuai', 'tidak sesuai']);
            $table->enum('assesment_nyeri', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_pernafasan', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_tekanan_nadi', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_tekanan_darah', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_suhu_tubuh', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_saturasi_oksigen', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_oksigen_inhalasi_o2', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_balance_cairan', ['sesuai', 'tidak sesuai']);
            $table->enum('menyiapkan_dan_memasang_infus_anak', ['sesuai', 'tidak sesuai']);
            $table->enum('menyiapkan_dan_memasang_infus_dewasa', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_dan_mendokumentasikan_7_benar_obat', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_per_oral_po', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_venous_iv', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_muskular_im', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_cutan_ic', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_sub_cutan_sc', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_supositori', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_vagina', ['sesuai', 'tidak sesuai']);
            $table->enum('memasang_catheter', ['sesuai', 'tidak sesuai']);
            $table->enum('mengoperasionalkan_ctg', ['sesuai', 'tidak sesuai']);
            $table->enum('mengoprasionalkan_ekg', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_nebulizer', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_transfusi_darah', ['sesuai', 'tidak sesuai']);
            $table->enum('memandikan_pasien', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_kompres_hangat', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_ganti_verban', ['sesuai', 'tidak sesuai']);
            $table->enum('memasang_ngt_ogt', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_pendidikan_kesehatan', ['sesuai', 'tidak sesuai']);
            $table->string('catatan')->nullable();
            $table->string('nip', 12);
            $table->foreign('nip')->references('nip')->on('users');
            $table->enum('status_validasi', ['tervalidasi', 'belum tervalidasi'])->default('belum tervalidasi');
            $table->string('validator', 12)->nullable();
            $table->foreign('validator')->references('nip')->on('users');
            $table->timestamp('waktu_validasi')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
        });

        Schema::create('logbook_pk_rawatjalan', function (Blueprint $table) {
            $table->id()->primary();
            $table->string('no_rm', 6);
            $table->foreign('no_rm')->references('no_rm')->on('pasien');
            $table->enum('serah_terima_dan_mengerjakan_dok_pasien_baru_dewasa_dan_anak', ['sesuai', 'tidak sesuai']);
            $table->enum('memasang_gelang_identitas_pasien_sesuai_prosedur', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_sbar_dan_tbak', ['sesuai', 'tidak sesuai']);
            $table->enum('assesment_resiko_jatuh', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_pernafasan', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_tekanan_nadi', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_tekanan_darah', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_suhu_tubuh', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_saturasi_oksigen', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_oksigen_inhalasi_o2', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_nebulizer', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_ganti_verban', ['sesuai', 'tidak sesuai']);
            $table->enum('mengoperasikan_ctg', ['sesuai', 'tidak sesuai']);
            $table->enum('mengoperasikan_usg', ['sesuai', 'tidak sesuai']);
            $table->enum('mengoprasikan_ekg', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_pemasangan_infus_dewasa', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_pemasangan_infus_anak_neonatus', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_dan_mendokumentasikan_7_benar_obat', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_per_oral_po', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_venous_iv', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_muskular_im', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_cutan_ic', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_sub_cutan_sc', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_supositori', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_vaginal', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_mata', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_sublingual', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_pendidikan_kesehatan', ['sesuai', 'tidak sesuai']);
            $table->string('catatan')->nullable();
            $table->string('nip', 12);
            $table->foreign('nip')->references('nip')->on('users');
            $table->enum('status_validasi', ['tervalidasi', 'belum tervalidasi'])->default('belum tervalidasi');
            $table->string('validator', 12)->nullable();
            $table->foreign('validator')->references('nip')->on('users');
            $table->timestamp('waktu_validasi')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
        });

        Schema::create('logbook_pk_perina', function (Blueprint $table) {
            $table->id()->primary();
            $table->string('no_rm', 6);
            $table->foreign('no_rm')->references('no_rm')->on('pasien');
            $table->enum('melakukan_resusitasi_bayi_baru_lahir', ['sesuai', 'tidak sesuai']);
            $table->enum('memasang_gelang_pasien_baru', ['sesuai', 'tidak sesuai']);
            $table->enum('menerima_dan_mengerjakan_dokumentasi_pasien_baru_neonatus', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_sbar_dan_tbak', ['sesuai', 'tidak sesuai']);
            $table->enum('mengoperasikan_cpap', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_oksigenasi_pemasangan_o2', ['sesuai', 'tidak sesuai']);
            $table->enum('mengoperasikan_ventilator', ['sesuai', 'tidak sesuai']);
            $table->enum('memasang_infus_umbilical', ['sesuai', 'tidak sesuai']);
            $table->enum('memasang_infus_neonatus_via_iv', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_dan_mendokumentasikan_7_benar_obat', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_per_oral_po', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_venous_iv', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_muskular_im', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_mata', ['sesuai', 'tidak sesuai']);
            $table->enum('memandikan_bayi', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_makan_via_ogt', ['sesuai', 'tidak sesuai']);
            $table->enum('memasang_ogt', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_pendidikan_kesehatan', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_pernafasan', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_tekanan_nadi', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_tekanan_darah', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_suhu_tubuh', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_saturasi_oksigen', ['sesuai', 'tidak sesuai']);
            $table->enum('assesment_resiko_jatuh', ['sesuai', 'tidak sesuai']);
            $table->string('catatan')->nullable();
            $table->string('nip', 12);
            $table->foreign('nip')->references('nip')->on('users');
            $table->enum('status_validasi', ['tervalidasi', 'belum tervalidasi'])->default('belum tervalidasi');
            $table->string('validator', 12)->nullable();
            $table->foreign('validator')->references('nip')->on('users');
            $table->timestamp('waktu_validasi')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
        });

        Schema::create('logbook_pk_ok', function (Blueprint $table) {
            $table->id()->primary();
            $table->string('no_rm', 6);
            $table->foreign('no_rm')->references('no_rm')->on('pasien');
            $table->enum('menerima_dan_mengerjakan_dokumentasi_pasien_tindakan_ok', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_sbar_dan_tbak', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_pernafasan', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_tekanan_nadi', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_tekanan_darah', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_suhu_tubuh', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_saturasi_oksigen', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_oksigen_inhalasi_o2', ['sesuai', 'tidak sesuai']);
            $table->enum('assesment_resiko_jatuh', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_dan_mendokumentasikan_7_benar_obat', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_per_oral_po', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_venous_iv', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_muskular_im', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_cutan_ic', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_sub_cutan_sc', ['sesuai', 'tidak sesuai']);
            $table->enum('pemasangan_catether', ['sesuai', 'tidak sesuai']);
            $table->enum('mempersiapkan_pasien_operasi', ['sesuai', 'tidak sesuai']);
            $table->enum('membantu_dokter_bedah_selama_operasi', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_identifikasi_pasien_yang_akan_dioperasi', ['sesuai', 'tidak sesuai']);
            $table->enum('menyiapkan_alat_yang_dibutuhkan_saat_operasi_berlangsung', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_pemasangan_sarung_meja_mayo_dengan_benar', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_penyusunan_instrument_dasar_dimeja_mayo_dengan_benar', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_teknik_aseptic_dan_antiseptic_daerah_operasi', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_cuci_tangan_bedah', ['sesuai', 'tidak sesuai']);
            $table->enum('penghitungan_instrument_dan_peralatan_prosedur_pembedahan', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_dokumentasi_sign_in_dan_sign_out', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_observasi_pasien_post_operasi', ['sesuai', 'tidak sesuai']);
            $table->string('catatan')->nullable();
            $table->string('nip', 12);
            $table->foreign('nip')->references('nip')->on('users');
            $table->enum('status_validasi', ['tervalidasi', 'belum tervalidasi'])->default('belum tervalidasi');
            $table->string('validator', 12)->nullable();
            $table->foreign('validator')->references('nip')->on('users');
            $table->timestamp('waktu_validasi')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
        });

        Schema::create('logbook_pk_icu', function (Blueprint $table) {
            $table->id()->primary();
            $table->string('no_rm', 6);
            $table->foreign('no_rm')->references('no_rm')->on('pasien');
            $table->enum('assesment_resiko_jatuh', ['sesuai', 'tidak sesuai']);
            $table->enum('menerima_dan_mengerjakan_dokumentasi_pasien_baru_dewasa_dan_anak', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_sbar_dan_tbak', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_pemasangan_infus_dewasa', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_pemasangan_infus_anak_dan_neonatus', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_pemasangan_ngt_ogt', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_pemasangan_ventilator', ['sesuai', 'tidak sesuai']);
            $table->enum('observasi_pasien_dengan_intubasi', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_personal_hygiene_pasien', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_pernafasan', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_tekanan_nadi', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_tekanan_darah', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_suhu_tubuh', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_saturasi_oksigen', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_oksigen_inhalasi_o2', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_oksigenasi_pemasangan_o2', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_prosedur_tranfusi', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_pasien_nebulizer', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_balance_cairan', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_dan_mendokumentasikan_7_benar_obat', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_per_oral_po', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_venous_iv', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_muskular_im', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_cutan_ic', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_supositori', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_vaginal', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_mata', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_sublingual', ['sesuai', 'tidak sesuai']);
            $table->enum('menghitung_tetesan_infus', ['sesuai', 'tidak sesuai']);
            $table->string('catatan')->nullable();
            $table->string('nip', 12);
            $table->foreign('nip')->references('nip')->on('users');
            $table->enum('status_validasi', ['tervalidasi', 'belum tervalidasi'])->default('belum tervalidasi');
            $table->string('validator', 12)->nullable();
            $table->foreign('validator')->references('nip')->on('users');
            $table->timestamp('waktu_validasi')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
        });

        Schema::create('logbook_bk', function (Blueprint $table) {
            $table->id()->primary();
            $table->string('no_rm', 6);
            $table->foreign('no_rm')->references('no_rm')->on('pasien');
            $table->enum('menerima_dan_mengerjakan_dokumentasi_pasien_baru', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_oksigen_inhalasi_o2', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_sbar_dan_tbak', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_pernafasan', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_tekanan_nadi', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_tekanan_darah', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_suhu_tubuh', ['sesuai', 'tidak sesuai']);
            $table->enum('mengukur_saturasi_oksigen', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_bimbingan_dan_penyuluhan', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_asuhan_kebidanan', ['sesuai', 'tidak sesuai']);
            $table->enum('membantu_proses_persalinan_normal', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_kebersihan_vulva_vulva_hygiene', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_observasi_kemajuan_persalinan_kala_i_ii_iii_dan_iv', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_vt_atau_vaginal_touche', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_observasi_djj', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_epistomi', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_hecting_perineum', ['sesuai', 'tidak sesuai']);
            $table->enum('resusitasi_bayi_baru_lahir_spontan', ['sesuai', 'tidak sesuai']);
            $table->enum('memasang_catheter_wanita', ['sesuai', 'tidak sesuai']);
            $table->enum('memasang_infus_dewasa', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_gym_ball', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_pijat_oksitosin', ['sesuai', 'tidak sesuai']);
            $table->enum('mengoperasionalkan_ctg', ['sesuai', 'tidak sesuai']);
            $table->enum('melakukan_dan_mendokumentasikan_7_benar_obat', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_per_oral_po', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_venous_iv', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_muskular_im', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_intra_cutan_ic', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_sub_cutan_sc', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_supositori', ['sesuai', 'tidak sesuai']);
            $table->enum('memberikan_obat_vaginal', ['sesuai', 'tidak sesuai']);
            $table->string('catatan')->nullable();
            $table->string('nip', 12);
            $table->foreign('nip')->references('nip')->on('users');
            $table->enum('status_validasi', ['tervalidasi', 'belum tervalidasi'])->default('belum tervalidasi');
            $table->string('validator', 12)->nullable();
            $table->foreign('validator')->references('nip')->on('users');
            $table->timestamp('waktu_validasi')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('logbook_pk_ugd');
        Schema::dropIfExists('logbook_pk_rawatinap');
        Schema::dropIfExists('logbook_pk_rawatjalan');
        Schema::dropIfExists('logbook_pk_perina');
        Schema::dropIfExists('logbook_pk_ok');
        Schema::dropIfExists('logbook_pk_icu');
        Schema::dropIfExists('logbook_bk');
    }
};
